### ISSUE TITLE
Can't install on Debian 13 Trixie (Linux/ARM64)

### ISSUE THREAD

**Issue by rfay** [php/frankenphp#2014]
### What happened?

In Debian 13 Trixie ARM64 the install with deb packages fails:

 `docker run -it --rm debian:trixie` and `sudo apt update && sudo apt install curl` then:
```
root@87c2d5b07b08:/# curl https://frankenphp.dev/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4172  100  4172    0     0  20848      0 --:--:-- --:--:-- --:--:-- 20860
📦 Detected apt. Installing FrankenPHP from DEB repository...
Hit:1 http://deb.debian.org/debian trixie InRelease
Hit:2 http://deb.debian.org/debian trixie-updates InRelease
Hit:3 http://deb.debian.org/debian-security trixie-security InRelease
Get:4 https://deb.henderkes.com stable InRelease [2550 B]
Get:5 https://deb.henderkes.com stable/main arm64 Packages [20.3 kB]
Fetched 22.8 kB in 0s (91.3 kB/s)
14 packages can be upgraded. Run 'apt list --upgradable' to see them.
Solving dependencies... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 frankenphp : Depends: ld-linux-aarch64 (>= 2.17) but it is not installable
              Depends: libphp-zts-84.so
Error: Unable to correct problems, you have held broken packages.
Error: The following information from --solver 3.0 may provide additional context:
   Unable to satisfy dependencies. Reached two conflicting decisions:
   1. frankenphp:arm64=1.9.1-1 is selected for install
   2. frankenphp:arm64 Depends ld-linux-aarch64 (>= 2.17)
      but none of the choices are installable:
      [no choices]
```

I tested with Trixie AMD64 and it works OK there.

### Build Type

Standalone binary

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

aarch64

### PHP configuration

```shell
Irrelevant, this is Debian packaging problem
```

### Relevant log output

```shell
Failure shown above.
```

**Comment by henderkes** [comment]
Thanks for the report, will be automatically fixed in ~1:30h.

**Comment by henderkes** [comment]
Fixed https://github.com/static-php/spc-packages/actions/runs/19592621610/job/56112919797.

Edit: Please keep in mind that if you're using Docker, there's a frankenphp base image. `FROM dunglas/frankenphp` see https://frankenphp.dev/docs/docker/.

```console
root@604e37493c3c:/# curl https://frankenphp.dev/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4172  100  4172    0     0   227k      0 --:--:-- --:--:-- --:--:--  239k
📦 Detected apt. Installing FrankenPHP from DEB repository...
Hit:1 http://deb.debian.org/debian trixie InRelease
Hit:2 http://deb.debian.org/debian trixie-updates InRelease
Hit:3 http://deb.debian.org/debian-security trixie-security InRelease
Get:4 https://deb.henderkes.com stable InRelease [2550 B]
Get:5 https://deb.henderkes.com stable/main arm64 Packages [20.3 kB]
Fetched 20.3 kB in 0s (173 kB/s)
All packages are up to date.
Installing:
  frankenphp

Installing dependencies:
  php-zts-cli  php-zts-embed

Summary:
  Upgrading: 0, Installing: 3, Removing: 0, Not Upgrading: 0
  Download size: 32.8 MB
  Space needed: 116 MB / 36.5 GB available

Get:1 https://deb.henderkes.com stable/main arm64 php-zts-cli arm64 8.4.15-1 [10.0 MB]
Get:2 https://deb.henderkes.com stable/main arm64 php-zts-embed arm64 8.4.15-1 [9830 kB]
Get:3 https://deb.henderkes.com stable/main arm64 frankenphp arm64 1.9.1-1 [13.0 MB]
Fetched 32.8 MB in 0s (99.1 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 79, <STDIN> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC entries checked: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.40.1 /usr/local/share/perl/5.40.1 /usr/lib/aarch64-linux-gnu/perl5/5.40 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl-base /usr/lib/aarch64-linux-gnu/perl/5.40 /usr/share/perl/5.40 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 8, <STDIN> line 3.)
debconf: falling back to frontend: Teletype
Selecting previously unselected package php-zts-cli.
(Reading database ... 6997 files and directories currently installed.)
Preparing to unpack .../php-zts-cli_8.4.15-1_arm64.deb ...
Unpacking php-zts-cli (8.4.15-1) ...
Selecting previously unselected package php-zts-embed.
Preparing to unpack .../php-zts-embed_8.4.15-1_arm64.deb ...
Unpacking php-zts-embed (8.4.15-1) ...
Selecting previously unselected package frankenphp.
Preparing to unpack .../frankenphp_1.9.1-1_arm64.deb ...
Unpacking frankenphp (1.9.1-1) ...
Setting up php-zts-cli (8.4.15-1) ...
Setting up php-zts-embed (8.4.15-1) ...
Setting up frankenphp (1.9.1-1) ...
useradd: warning: the home directory /var/lib/frankenphp already exists.
useradd: Not copying any file from skel directory into it.
/usr/sbin/policy-rc.d returned 101, not running 'start frankenphp.service'
2025/11/22 09:36:37.924 INFO    maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2025/11/22 09:36:37.924 INFO    GOMEMLIMIT is updated   {"package": "github.com/KimMachineGun/automemlimit/memlimit", "GOMEMLIMIT": 22631631667, "previous": 9223372036854775807}
2025/11/22 09:36:37.924 INFO    using config from file  {"file": "/dev/null"}
2025/11/22 09:36:37.925 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//[::1]:2019", "//127.0.0.1:2019", "//localhost:2019"]}
2025/11/22 09:36:37.926 INFO    serving initial configuration
2025/11/22 09:36:37.928 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2019", "uri": "/pki/ca/local", "remote_ip": "127.0.0.1", "remote_port": "42830", "headers": {"Accept-Encoding":["gzip"],"Origin":["http://localhost:2019"],"User-Agent":["Go-http-client/1.1"]}}
2025/11/22 09:36:37.940 WARN    installing root certificate (you might be prompted for password)        {"path": "localhost:2019/pki/ca/local"}
2025/11/22 09:36:37.940 INFO    warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
2025/11/22 09:36:37.940 INFO    define JAVA_HOME environment variable to use the Java trust
2025/11/22 09:36:38.711 INFO    certificate installed properly in linux trusts
2025/11/22 09:36:38.715 INFO    shutting down apps, then terminating    {"signal": "SIGTERM"}
2025/11/22 09:36:38.715 WARN    exiting; byeee!! 👋     {"signal": "SIGTERM"}
2025/11/22 09:36:38.715 INFO    admin   stopped previous server {"address": "localhost:2019"}
2025/11/22 09:36:38.715 INFO    shutdown complete       {"signal": "SIGTERM", "exit_code": 0}

🥳 FrankenPHP installed successfully.

⭐ If you like FrankenPHP, please give it a star on GitHub: https://github.com/php/frankenphp
root@604e37493c3c:/# frankenphp -v
FrankenPHP v1.9.1 PHP 8.4 Caddy v2.10.2 h1:g/gTYjGMD0dec+UgMw8SnfmJ3I9+M2TdvoRL/Ovu6U8=
```

**Comment by rfay** [comment]
Thanks!

**Comment by nmolham-godaddy** [comment]
hi @henderkes I think this issue resurfaced again, running on `debian:bookworm-slim` ARM64 [official PHP 8.4 docker image](https://github.com/docker-library/php/blob/master/8.4/bookworm/cli/Dockerfile).

```docker
RUN curl -fsSL https://key.henderkes.com/static-php.gpg -o /usr/share/keyrings/static-php.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/static-php.gpg] https://deb.henderkes.com/ stable main" | tee /etc/apt/sources.list.d/static-php.list

RUN apt-get update && apt-get -y install frankenphp
```

```log
4.484 Reading package lists...
4.728 Building dependency tree...
4.783 Reading state information...
4.802 Some packages could not be installed. This may mean that you have
4.802 requested an impossible situation or if you are using the unstable
4.802 distribution that some required packages have not yet been created
4.802 or been moved out of Incoming.
4.802 The following information may help to resolve the situation:
4.802
4.802 The following packages have unmet dependencies:
4.842  frankenphp : Depends: libphp-zts-84.so
4.844 E: Unable to correct problems, you have held broken packages.
```

I understand there is a frankenphp base image, but due to some company guidelines, I can use it.

**Comment by henderkes** [comment]
Hi, that repository has been deprecated in favour of the ones where you can choose the version.

It does however work for me, given that you posted this 7 hours, suspiciously close to when the repository was being updated, it might have just been the one minute where you got an incomplete version of metadata. That's also a reason why it's deprecated.

The new instructions for php 8.4 (replace with the version you want) are 
```bash
sudo curl https://pkg.henderkes.com/api/packages/84/debian/repository.key -o /etc/apt/keyrings/static-php84.asc
echo "deb [signed-by=/etc/apt/keyrings/static-php84.asc] https://pkg.henderkes.com/api/packages/84/debian php-zts main" | sudo tee /etc/apt/sources.list.d/static-php84.list
sudo apt update && sudo apt install -y frankenphp
```

or simply:

```bash
curl -fsSL https://files.henderkes.com/install.sh | sudo sh -s 8.4
```

```bash
❯❯ m  10:02 docker run -it --rm debian:bookworm-slim
root@359b13a25161:/# apt update &> /dev/null && apt install -y sudo curl &> /dev/null
root@359b13a25161:/# curl -fsSL https://key.henderkes.com/static-php.gpg -o /usr/share/keyrings/static-php.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/static-php.gpg] https://deb.henderkes.com/ stable main" | tee /etc/apt/sources.list.d/static-php.list
deb [signed-by=/usr/share/keyrings/static-php.gpg] https://deb.henderkes.com/ stable main
root@359b13a25161:/# apt-get update &> /dev/null && apt-get -y install frankenphp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  php-zts-cli php-zts-embed
The following NEW packages will be installed:
  frankenphp php-zts-cli php-zts-embed
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 32.5 MB of archives.
After this operation, 135 MB of additional disk space will be used.
Get:1 https://deb.henderkes.com stable/main amd64 php-zts-cli amd64 8.4.17-1 [9461 kB]
Get:2 https://deb.henderkes.com stable/main amd64 php-zts-embed amd64 8.4.17-1 [9350 kB]
Get:3 https://deb.henderkes.com stable/main amd64 frankenphp amd64 1.11.1+php84-1 [13.7 MB]
Fetched 32.5 MB in 3s (12.7 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package php-zts-cli.
(Reading database ... 6895 files and directories currently installed.)
Preparing to unpack .../php-zts-cli_8.4.17-1_amd64.deb ...
Unpacking php-zts-cli (8.4.17-1) ...
Selecting previously unselected package php-zts-embed.
Preparing to unpack .../php-zts-embed_8.4.17-1_amd64.deb ...
Unpacking php-zts-embed (8.4.17-1) ...
Selecting previously unselected package frankenphp.
Preparing to unpack .../frankenphp_1.11.1+php84-1_amd64.deb ...
Unpacking frankenphp (1.11.1+php84-1) ...
Setting up php-zts-cli (8.4.17-1) ...

================================================================================
                          ⚠️  DEPRECATION NOTICE
================================================================================

The single-version php-zts repository is deprecated and will no longer receive updates.

Please migrate to the new repository with different PHP versions available.

More information: https://pkgs.henderkes.com

================================================================================

Setting up php-zts-embed (8.4.17-1) ...

================================================================================
                          ⚠️  DEPRECATION NOTICE
================================================================================

This repository is deprecated and will no longer receive updates.

Please migrate to the new repository with different PHP versions available.

More information: https://pkgs.henderkes.com

================================================================================

Setting up frankenphp (1.11.1+php84-1) ...

================================================================================
                          ⚠️  DEPRECATION NOTICE
================================================================================

The single-version php-zts repository is deprecated and will no longer receive updates.

Please migrate to the new repository with different PHP versions available.

More information: https://pkgs.henderkes.com

================================================================================

2026/01/21 09:04:27.104 INFO    maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
2026/01/21 09:04:27.104 INFO    GOMEMLIMIT is updated   {"package": "github.com/KimMachineGun/automemlimit/memlimit", "GOMEMLIMIT": 30248176435, "previous": 9223372036854775807}
2026/01/21 09:04:27.104 INFO    using config from file  {"file": "/dev/null"}
2026/01/21 09:04:27.126 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//[::1]:2019", "//127.0.0.1:2019", "//localhost:2019"]}
2026/01/21 09:04:27.126 INFO    serving initial configuration
2026/01/21 09:04:29.105 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2019", "uri": "/pki/ca/local", "remote_ip": "127.0.0.1", "remote_port": "48824", "headers": {"Accept-Encoding":["gzip"],"Origin":["http://localhost:2019"],"User-Agent":["Go-http-client/1.1"]}}
2026/01/21 09:04:29.115 WARN    installing root certificate (you might be prompted for password)        {"path": "localhost:2019/pki/ca/local"}
2026/01/21 09:04:29.115 INFO    warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
2026/01/21 09:04:29.115 INFO    define JAVA_HOME environment variable to use the Java trust
2026/01/21 09:04:30.091 INFO    certificate installed properly in linux trusts
2026/01/21 09:04:30.096 INFO    shutting down apps, then terminating    {"signal": "SIGTERM"}
2026/01/21 09:04:30.096 WARN    exiting; byeee!! 👋     {"signal": "SIGTERM"}
2026/01/21 09:04:30.096 INFO    admin   stopped previous server {"address": "localhost:2019"}
2026/01/21 09:04:30.096 INFO    shutdown complete       {"signal": "SIGTERM", "exit_code": 0}
```

**Comment by nmolham-godaddy** [comment]
@henderkes thanks for responding, not what I am doing wrong from my end, but I tried the updated instructions for 8.4 and got the exact same error:

```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
frankenphp : Depends: libphp-zts-84.so
E: Unable to correct problems, you have held broken packages.
```

I also tried the `install.sh` script, it does install PHP ZTS repo, but still unable to install frankenphp, same error

```
deb [signed-by=/etc/apt/keyrings/henderkes84.asc] https://pkg.henderkes.com/api/packages/84/debian php-zts main
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8691 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [6936 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [287 kB]
Get:7 https://pkg.henderkes.com/api/packages/84/debian php-zts InRelease [3301 B]
Get:8 https://pkg.henderkes.com/api/packages/84/debian php-zts/main arm64 Packages [110 kB]
Fetched 9353 kB in 2s (5472 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
Repository added to /etc/apt/sources.list.d/static-php84.list
Successfully installed PHP ZTS repository (version 84)
```

FYI, tried the [official install script](https://github.com/php/frankenphp?tab=readme-ov-file#install-script), same error

**Comment by henderkes** [comment]
I suspect you have poisoned your environment somehow. Can you please checks your /etc/sources.list.d/ and /usr/share/keyrings folders and delete everything from me to restore a clean slate?

Can you reproduce the error in a Docker container and if so, can you tell me exactly how?

**Comment by nmolham-godaddy** [comment]
Sorry @henderkes I missed your commend 🙏 

> Can you reproduce the error in a Docker container and if so, can you tell me exactly how?

All in docker from the beginning, the container is based on the [official docker 8.4 image](https://github.com/docker-library/php/blob/master/8.4/bookworm/fpm/Dockerfile) which in-turn based on `debian:bookworm-slim`

> I suspect you have poisoned your environment somehow.

That was my suspension too. But I can install any other debian package without issues, including php extensions 🤷‍♂️ 

I actually ended up going with a different approach, which worked at the end

```Dockerfile
RUN ARCH=$(uname -m) && \
    curl --fail -L -O "https://github.com/php/frankenphp/releases/download/v1.11.1/frankenphp-linux-${ARCH}" && \
    mv frankenphp-linux-${ARCH} frankenphp && chmod +x frankenphp && \
    chown www-data:www-data frankenphp && ./frankenphp version
```

**Comment by henderkes** [comment]
> All in docker from the beginning, the container is based on the [official docker 8.4 image](https://github.com/docker-library/php/blob/master/8.4/bookworm/fpm/Dockerfile) which in-turn based on debian:bookworm-slim

Well that could explain it, why are you trying to install FrankenPHP debian packages in a php Docker container?

> RUN ARCH=$(uname -m) && \
    curl --fail -L -O "https://github.com/php/frankenphp/releases/download/v1.11.1/frankenphp-linux-${ARCH}" && \
    mv frankenphp-linux-${ARCH} frankenphp && chmod +x frankenphp && \
    chown www-data:www-data frankenphp && ./frankenphp version

This is not recommended for production use. Or in a Docker container in general.

Why aren't you using the FrankenPHP Docker images? https://frankenphp.dev/docs/docker/

**Comment by nmolham-godaddy** [comment]
> why are you trying to install FrankenPHP debian packages in a php Docker container?
> Why aren't you using the FrankenPHP Docker images?

Due to company's policy, I can't use any 3rd party docker containers, it has to be from a pre-approved list.
That is why I ended trying to use debian package instead.

> Well that could explain it

What is the explanation? 👀

**Comment by henderkes** [comment]
The regular php (NTS) version compiled in Docker conflicts with the ZTS version provided by the Debian packages.

Perhaps you can just use a bookworm-slim image directly? Less space wasted, too.

**Comment by nmolham-godaddy** [comment]
> The regular php (NTS) version compiled in Docker conflicts with the ZTS version provided by the Debian packages.

Ah, I see, but why installing 1.9.1 deb package worked? but not 1.11.1 ? 🤔 

```Dockerfile
RUN ARCH=$(dpkg --print-architecture) && \
    curl --fail -L -O "https://github.com/php/frankenphp/releases/download/v1.9.1/frankenphp_1.9.1-1_${ARCH}.deb" && \
    dpkg -i "frankenphp_1.9.1-1_${ARCH}.deb" && \
    rm "frankenphp_1.9.1-1_${ARCH}.deb"
```

> Perhaps you can just use a bookworm-slim image directly? Less space wasted, too.

Good point

> This is not recommended for production use. Or in a Docker container in general.

Why?

Sorry for the multiple follow up questions 😄 I am taking too much of your time

**Comment by henderkes** [comment]
> > The regular php (NTS) version compiled in Docker conflicts with the ZTS version provided by the Debian packages.
> 
> Ah, I see, but why installing 1.9.1 deb package worked? but not 1.11.1 ? 🤔
> 
> RUN ARCH=$(dpkg --print-architecture) && \
>     curl --fail -L -O "https://github.com/php/frankenphp/releases/download/v1.9.1/frankenphp_1.9.1-1_${ARCH}.deb" && \
>     dpkg -i "frankenphp_1.9.1-1_${ARCH}.deb" && \
>     rm "frankenphp_1.9.1-1_${ARCH}.deb"

Because the deb packages that were attached here were still the statically linked version without precompiled extension support. Now we have real system packages that include the required ZTS build of php. Apparently something in Docker conflicts with php-zts-embed. I'll try to figure it out later, because the packages are designed so that you can use them alongside Ondrejs/Remis.

> > This is not recommended for production use. Or in a Docker container in general.
> 
> Why?

Out of compatibility reasons the static binary is linked against a very old glibc version and optimised for size, rather than speed.

> Sorry for the multiple follow up questions 😄 I am taking too much of your time

All good!

**Comment by henderkes** [comment]
@nmolham-godaddy the docker image installs `/etc/apt/preferences.d/no-debian-php` to make sure that no debian packages are installed that provide php.

Tl;dr: don't use the base php (NTS) images when you want to use FrankenPHP. They're incompatible.
Either use a base image and install the apt packages, or (might work with company guidelines) use `php:8.4-zts-bookworm` as a base image and then compile frankenphp from sources in a build step. But that would also require using go/xcaddy or frankenphp base images, which may be an issue again.
